### PR TITLE
Bump to 8.2

### PR DESCRIPTION
**Pull request by ktheticdev**
Tried to update to 8.2

### CODE REVIEW

**Comment by ktheticdev** [comment]
gotta fix authlib injector issues

**Comment by LunaisLazier** [comment]
you also broke the curseforge api key stuff with this update uhhhh

**Comment by ktheticdev** [comment]
zamn
I'll try to fix ty

**Comment by ktheticdev** [comment]
seems to work fine for me with the default API key tho

**Comment by evan-goode** [comment]
Yeah there are a few regressions in this PR, including adding back in Prism Launcher's MSA client ID... :)

I did a merge of 8.2 as well and there weren't a ton of conflicts, feel free to use this: 
https://github.com/unmojang/PollyMC/tree/unmojang/8.2.

Also I think it would be great to merge/close the other outstanding PRs before releasing 8.2, there are some important fixes waiting. But we'll see what @fn2006 thinks when he comes around.

**Comment by ktheticdev** [comment]
closing as there is a better merge

**Comment by evan-goode** [comment]
OK I opened a PR for my branch: https://github.com/fn2006/PollyMC/pull/161

**Pull request closed without merging**
